#! /usr/bin/env bash

cd $(dirname $0)/..

while true; do

    inotifywait -e modify Makefile src/scruple.c src/scruple.scm test/tests.sql

    make
    make install
    pg_prove -U postgres test/tests.sql

done
