#!/usr/bin/env bash

pg_ctlcluster $1 test start

cd /repo
make
make install

cd /opt/src/pgtap/pgtap-$PGTAP_VERSION
make
make install

psql -U postgres <<EOF

create extension if not exists pgtap;
create extension if not exists plguile3;

EOF
