#! /usr/bin/env bash

cd $(dirname $0)/..

CONTAINER_NAME=scruple-test-$1

docker stop $CONTAINER_NAME >/dev/null 2>&1 || true
docker rm $CONTAINER_NAME >/dev/null 2>&1 || true

# Path to scruple repo inside of the container

docker run \
       -t \
       -d \
       -w /repo \
       --name $CONTAINER_NAME \
       --mount "type=bind,src=$(pwd),dst=/repo" \
       scruple-test \
       bash -c "

cd /repo/test

./prepare-test-db $1
./build-monitor

"
