#! /usr/bin/env bash

cd $(dirname $0)/..

IMAGE_NAME=plguile3-test-$1
CONTAINER_NAME=plguile3-test-$1

docker stop $CONTAINER_NAME >/dev/null 2>&1 || true
docker rm $CONTAINER_NAME >/dev/null 2>&1 || true

# Path to plguile3 repo inside of the container

docker run \
       -t \
       -d \
       -w /repo \
       --name $CONTAINER_NAME \
       --mount "type=bind,src=$(pwd),dst=/repo" \
       $IMAGE_NAME \
       bash -c "cd /repo/test && ./prepare-test-db $1 && ./change-monitor"
