#! /usr/bin/env bash

cd $(dirname $0)/..

inotifywait -e modify \
            Makefile \
            plguile3--1.0.sql \
            src/plguile3.c \
            src/plguile3.scm \
            src/modules/pg/types.scm \
            test/Makefile \
            test/concurrent/user_env.sql \
            test/tests.sql
